### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5' on MacOs

### ISSUE THREAD

**Issue by olena-palii** [krmanik/Sentence-Adder-Anki-Addon#25]
Other addons don't need it so I guess that it's not ok?

Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-13.5.2-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-23 21:25:04

When loading Sentence adder for any language with batch add option:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/lenanetka/Library/Application Support/Anki2/addons21/1682655437/__init__.py", line 22, in <module>
    from PyQt5 import QtWidgets, QtCore
ModuleNotFoundError: No module named 'PyQt5'

**Comment by Lilneo786** [comment]
open a terminal in ur macoS and check if you have pip installed: `pip --version`

if you dont have it installed then install it: `python -m ensurepip --default-pip`

Activate your Anki Python environment 
and install:

`pip install PyQt5`

**Comment by Lenanetka** [comment]
Thank you, I thought about it but raised a bug because it was not mentioned as "must do" in description and all my other addons don't need to install something. You can close the bug if you are sure that it doesn't need any changes.

**Comment by krmanik** [comment]
Next version will have the fix.

**Comment by krmanik** [comment]
I have updated the addon try again and let me know if it is solved or not.

**Comment by krmanik** [comment]
It is fixed in version 1.1.0, try again. If issues still persist then reopen.
